0411 function
tigerscave/mamadou-scheme pull request #28
Opened 2019-04-11 03:52 UTC by bintabaldeh

2019-04-11 03:52 UTC, bintabaldeh commented
how about this one

2019-04-11 11:50 UTC, hrl7 requested changes

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +            (else (cons (car l)
fix this indent

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +              (else (cons (rember* a(car l))
also here

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +  (lambda (lat)
even it is a "star" function, is this `lat`? really?

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +  (and (not (null? x)) (not (pair? x)))))
this `and` is inside of lambda. so you need one more indent

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +              (rm-even* (cdr lat)))))))
in this function, the indentations are good! :+1:

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +(define sum-tup*
it's not a "star" function.
if this is named `sum-tup`, you are right.
now I recommend to change the name to `sum-tup`. 
later let's rewrite this.

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +    ((null? tup) 0)
the indent is wrong

2019-04-11 11:50 UTC, hrl7 commented on 0411.scm
> +(print (tup-sum '(1 2 3 4)))
I need one more empty line above since we want to separate the definition and others.

2019-04-18 13:50 UTC, hrl7 approved these changes

2019-04-18 13:50 UTC, merged